# Generated by Django 3.0 on 2019-12-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=500)),
                ('teamName', models.CharField(max_length=200)),
                ('emailT1', models.EmailField(max_length=254)),
                ('emailT2', models.EmailField(max_length=254)),
                ('contactT1', models.CharField(max_length=10)),
                ('contactT2', models.CharField(max_length=20)),
                ('nameT1', models.CharField(max_length=50)),
                ('nameT2', models.CharField(max_length=50)),
                ('teamId', models.CharField(max_length=20)),
                ('nameTeacher', models.CharField(max_length=50)),
                ('emailTeacher', models.EmailField(max_length=254)),
                ('contactTeacher', models.CharField(max_length=20)),
                ('schoolAddress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('A', models.CharField(max_length=1000)),
                ('B', models.CharField(max_length=1000)),
                ('C', models.CharField(max_length=1000)),
                ('D', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1)),
                ('acutalAnswer', models.CharField(max_length=1)),
            ],
        ),
    ]
