# Generated by Django 3.0 on 2019-12-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathonTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, max_length=20, null=True)),
                ('A1', models.CharField(blank=True, max_length=1, null=True)),
                ('A2', models.CharField(blank=True, max_length=1, null=True)),
                ('A3', models.CharField(blank=True, max_length=1, null=True)),
                ('A4', models.CharField(blank=True, max_length=1, null=True)),
                ('A5', models.CharField(blank=True, max_length=1, null=True)),
                ('A6', models.CharField(blank=True, max_length=1, null=True)),
                ('A7', models.CharField(blank=True, max_length=1, null=True)),
                ('A8', models.CharField(blank=True, max_length=1, null=True)),
                ('A9', models.CharField(blank=True, max_length=1, null=True)),
                ('A10', models.CharField(blank=True, max_length=1, null=True)),
                ('A12', models.CharField(blank=True, max_length=1, null=True)),
                ('A13', models.CharField(blank=True, max_length=1, null=True)),
                ('A14', models.CharField(blank=True, max_length=1, null=True)),
                ('A15', models.CharField(blank=True, max_length=1, null=True)),
                ('A16', models.CharField(blank=True, max_length=1, null=True)),
                ('A17', models.CharField(blank=True, max_length=1, null=True)),
                ('A18', models.CharField(blank=True, max_length=1, null=True)),
                ('A19', models.CharField(blank=True, max_length=1, null=True)),
                ('A20', models.CharField(blank=True, max_length=1, null=True)),
                ('A21', models.CharField(blank=True, max_length=1, null=True)),
                ('A22', models.CharField(blank=True, max_length=1, null=True)),
                ('A23', models.CharField(blank=True, max_length=1, null=True)),
                ('A24', models.CharField(blank=True, max_length=1, null=True)),
                ('A25', models.CharField(blank=True, max_length=1, null=True)),
                ('A26', models.CharField(blank=True, max_length=1, null=True)),
                ('A27', models.CharField(blank=True, max_length=1, null=True)),
                ('A28', models.CharField(blank=True, max_length=1, null=True)),
                ('A29', models.CharField(blank=True, max_length=1, null=True)),
                ('A30', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='acutalAnswer',
        ),
        migrations.AlterField(
            model_name='profile',
            name='contactT1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nameTeacher',
            field=models.CharField(max_length=20),
        ),
    ]
