# Generated by Django 3.0 on 2019-12-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathonTest', '0002_auto_20191206_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='A11',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
