# Generated by Django 3.0 on 2019-12-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathonTest', '0006_auto_20191206_1158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionQuiz',
        ),
    ]
