# Generated by Django 3.0 on 2019-12-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathonTest', '0007_delete_questionquiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionQuiz',
            fields=[
                ('qId', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('A', models.CharField(max_length=1000)),
                ('B', models.CharField(max_length=1000)),
                ('C', models.CharField(max_length=1000)),
                ('D', models.CharField(max_length=1000)),
            ],
        ),
    ]
